'use client';

/**
 * Icon — single control point for every functional icon in the app.
 * Phosphor Icons, weight "duotone", currentColor. Swap a glyph here and it
 * changes everywhere. Sizes: 22px nav (default) · 20px buttons/tables.
 */
import type { ComponentProps } from 'react';
import { cn } from '@/lib/cn';
import {
  Alarm,
  Anchor,
  Archive,
  ArrowDown,
  ArrowSquareOut,
  ArrowUp,
  ArrowUUpLeft,
  ArrowsClockwise,
  ArrowsMerge,
  Boat,
  BookOpen,
  Broadcast,
  Buildings,
  CalendarBlank,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartBar,
  ChatCircleDots,
  Check,
  CheckCircle,
  ClipboardText,
  Clock,
  Copy,
  Crane,
  CreditCard,
  Desktop,
  DeviceMobile,
  DotsThree,
  DownloadSimple,
  Drop,
  EnvelopeSimple,
  Export,
  Eye,
  Factory,
  FileDoc,
  FilePdf,
  FileText,
  FileXls,
  FloppyDisk,
  Folder,
  Gear,
  HardHat,
  Hourglass,
  House,
  Image as ImageIcon,
  Info,
  Kanban,
  Lightning,
  LinkSimple,
  LockKey,
  MagnifyingGlass,
  MapPin,
  MapTrifold,
  Money,
  NotePencil,
  Package,
  Paperclip,
  PencilSimple,
  Percent,
  Phone,
  Plus,
  Printer,
  Prohibit,
  PushPin,
  Receipt,
  Robot,
  Ruler,
  Scroll,
  SignOut,
  Sparkle,
  TestTube,
  Trash,
  Tray,
  TrayArrowDown,
  TrendUp,
  Trophy,
  Truck,
  UploadSimple,
  User,
  Users,
  UsersThree,
  WarningCircle,
  WhatsappLogo,
  Wrench,
  X,
  XCircle,
  type Icon as PhosphorIcon,
} from '@phosphor-icons/react';

export const ICONS = {
  // ניווט / מודולים
  dashboard: House,
  projects: Kanban,
  drawings: Ruler,
  customers: Users,
  import: Boat,
  logistics: Truck,
  production: Factory,
  forms: FileText,
  settings: Gear,
  field: HardHat,
  inventory: Package,
  reports: TrendUp,
  marketing: ChartBar,
  logout: SignOut,
  ai: Sparkle,

  // פעולות
  search: MagnifyingGlass,
  add: Plus,
  edit: PencilSimple,
  delete: Trash,
  confirm: Check,
  close: X,
  save: FloppyDisk,
  copy: Copy,
  refresh: ArrowsClockwise,
  restore: ArrowUUpLeft,
  archive: Archive,
  merge: ArrowsMerge,
  print: Printer,
  send: Export,
  upload: UploadSimple,
  download: DownloadSimple,
  attach: Paperclip,
  link: LinkSimple,
  external: ArrowSquareOut,
  camera: Camera,

  // סטטוס / משוב
  warning: WarningCircle,
  success: CheckCircle,
  error: XCircle,
  blocked: Prohibit,
  pending: Clock,
  loading: Hourglass,
  expired: Alarm,
  info: Info,
  eye: Eye,

  // ישויות / דומיין
  file: FileText,
  pdf: FilePdf,
  image: ImageIcon,
  excel: FileXls,
  doc: FileDoc,
  folder: Folder,
  inbox: TrayArrowDown,
  empty: Tray,
  package: Package,
  ship: Boat,
  truck: Truck,
  anchor: Anchor,
  satellite: Broadcast,
  map: MapTrifold,
  invoice: Receipt,
  lab: TestTube,
  money: Money,
  payment: CreditCard,
  contract: Scroll,
  calendar: CalendarBlank,
  pin: PushPin,
  note: NotePencil,
  clipboard: ClipboardText,
  spec: ClipboardText,
  chart: ChartBar,
  trend: TrendUp,
  percent: Percent,
  book: BookOpen,
  trophy: Trophy,
  construction: Crane,
  location: MapPin,
  phone: Phone,
  email: EnvelopeSimple,
  whatsapp: WhatsappLogo,
  chat: ChatCircleDots,
  mobile: DeviceMobile,
  desktop: Desktop,
  user: User,
  company: Buildings,
  team: UsersThree,
  robot: Robot,
  wrench: Wrench,
  gear: Gear,
  lock: LockKey,
  zap: Lightning,
  drop: Drop,

  // חיצים / קיפול
  caretDown: CaretDown,
  caretUp: CaretUp,
  caretLeft: CaretLeft,
  caretRight: CaretRight,
  prev: CaretRight, // RTL: "הקודם" מצביע ימינה
  next: CaretLeft, //  RTL: "הבא" מצביע שמאלה
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  more: DotsThree,
} as const satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof ICONS;

interface IconProps {
  name: IconName;
  /** 22 בניווט (ברירת מחדל) · 20 בכפתורים/טבלאות */
  size?: number;
  weight?: ComponentProps<PhosphorIcon>['weight'];
  className?: string;
}

export default function Icon({ name, size = 22, weight = 'duotone', className }: IconProps) {
  const Glyph = ICONS[name];
  // inline-block + align: מתיישר עם טקסט עברי בשורה כמו האמוג׳י שהוא מחליף
  return <Glyph size={size} weight={weight} color="currentColor" className={cn('inline-block align-[-0.2em] shrink-0', className)} aria-hidden />;
}
